version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    reviewers:
      - "elopez"
      - "montyly"
