#!/usr/bin/env python3
import urllib.request
import json
import os
import argparse
import re

home_dir = os.path.expanduser('~')
solc_select_dir = f"{home_dir}/.solc-select"
artifacts_dir = f"{solc_select_dir}/artifacts"

# all versions take 1.5G
# $ du -sh ~/.solc-select/artifacts/
# 1.5G    /Users/artur/.solc-select/artifacts/
# versions can be empty - install all versions
def download_all(versions):
    list_json = urllib.request.urlopen('https://binaries.soliditylang.org/macosx-amd64/list.json').read()
    releases = json.loads(list_json)["releases"]

    for version, artifact in releases.items():
        if versions and version not in versions:
            continue

        url = f"https://binaries.soliditylang.org/macosx-amd64/{artifact}"
        print("Installed", version)
        artifact_file = f"{artifacts_dir}/solc-{version}"
        urllib.request.urlretrieve(url, artifact_file)
        os.chmod(artifact_file, 0o775) # TODO rethink permissions

def switch_global_version(version):
    if os.path.isfile(f"{artifacts_dir}/solc-{version}"):
        with open(f"{solc_select_dir}/global-version", "w") as f: f.write(version)
        print("Switched global version to",version)
    else:
        print("unknown version") # TODO work on message
    
def valid_version(version): 
    # check that it matches <digit>.<digit>.<digit>
    match = re.search("^(\d+).(\d+).(\d+)$",version)
    if match is None:
        raise argparse.ArgumentTypeError("Invalid Solidity version " + version)
    return version

def installed_versions():
    all_installed_versions = os.listdir(artifacts_dir)
    all_installed_versions.sort()

    print("Available versions: ")
    for version in all_installed_versions:
        print(version)


INSTALL_VERSIONS = "INSTALL_VERSIONS"
USE_VERSION = "USE_VERSION"
INSTALLED_VERSIONS = "INSTALLED_VERSIONS"

parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(help='TODO')
parser_install = subparsers.add_parser('install', help='a help')
parser_install.add_argument(INSTALL_VERSIONS, help='TODO', nargs="*", default=list(), type=valid_version)
parser_use = subparsers.add_parser('use', help='TODO')
parser_use.add_argument(USE_VERSION, help='Expecting version similar to 0.4.25', type=valid_version)
parser_use = subparsers.add_parser('installed-versions', help='TODO')
parser_use.add_argument(INSTALLED_VERSIONS, help='TODO', nargs="*", default=list())
parser.parse_args()

args = vars(parser.parse_args())
print(args)

if args.get(INSTALL_VERSIONS) is not None:
    download_all(args.get(INSTALL_VERSIONS))

if args.get(USE_VERSION) is not None:
    switch_global_version(args.get(USE_VERSION))

if args.get(INSTALLED_VERSIONS) is not None:
    installed_versions()
