#!/usr/bin/env python3
import os
import solc_select
import sys

res = solc_select.current_version()
if res:
    (version, _) = res
else:
    exit(1)

path = f"{solc_select.artifacts_dir}/solc-{version}"
os.execv(path, [path] + sys.argv[1:])
