#!/bin/bash

OS=$(uname)

#
# Install locally on Linux

if [ $OS = "Linux" ]; then
    echo "Detected Linux"

    REPO_SCRIPTDIR=`dirname "$0"`
    cd $REPO_SCRIPTDIR

    if [ ! -f ./install_linux.sh ]; then
        echo "Cannot find Linux installation script. If you are installing via Docker - it is unecessary on Linux, instead refer to Linux installation instructions in README.md"
        exit 1
    fi

    bash install_linux.sh

    exit $?
fi


#
# Install globally or at $PREFIX on OS X

if [ -z "$PREFIX" ]; then
    EXISTING_SOLC_PATH=`which solc`
    if [ $? -ne 0 ]; then
        # solc isn't yet installed
        EXISTING_SOLC_PATH='/usr/bin/solc'
    fi
else
    EXISTING_SOLC_PATH="$PREFIX/bin/solc"
fi

if [ -f $EXISTING_SOLC_PATH ]; then
    read -p "Overwrite ${EXISTING_SOLC_PATH}? [yN] " -r </dev/tty
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1 || return 1
    fi
fi

finalize () {
    echo "Installed solc to ${EXISTING_SOLC_PATH}"
}


# The remainder of this script is auto-generated by the Dockerfile
cat >$EXISTING_SOLC_PATH << 'EOF'
