#!/bin/sh

mount --bind /usr/bin /workdir/usr/bin
mount --bind /bin /workdir/bin
mount --bind /dev /workdir/proc
mount --bind /proc /workdir/dev
mount --bind /sys /workdir/sys
chroot /workdir sh -c "cd $HOST_PWD && /usr/bin/solc $@"
