name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    name: CI (Python ${{ matrix.python }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: ["ubuntu-latest", "ubuntu-24.04-arm", "macos-latest", "macos-15-intel", "windows-2022"]
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false
    - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
      with:
        python-version: ${{ matrix.python }}
    - name: Install QEMU and libc
      if: matrix.os == 'ubuntu-24.04-arm'
      run: |
        sudo apt-get update
        sudo apt-get -y install qemu-user libc6-amd64-cross
        echo QEMU_LD_PREFIX=/usr/x86_64-linux-gnu >> "$GITHUB_ENV"
    - name: Install solc-select and test dependencies
      run: |
        uv sync --extra dev
    - name: Run Tests
      run: |
        uv run python -m pytest tests/ -v --tb=short -n auto -m "not slow"
