name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"            
        type: ["solc_upgrade", "linux","solc"]
    steps:    
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install solc-select
      run: |
        sudo python3 setup.py install
        solc-select install all
    - name: Run Tests
      env:
        TEST_TYPE: ${{ matrix.type }}
      run: |
        bash scripts/test_${TEST_TYPE}.sh